language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install -Pqulice,cobertura,coveralls --errors
after_success:
  - mvn clean install -Pcobertura coveralls:report
